/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoRouteImport } from './routes/go'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125WritingRouteImport } from './routes/{-$locale}/writing'
import { Route as Char123LocaleChar125VoiceRouteImport } from './routes/{-$locale}/voice'
import { Route as Char123LocaleChar125VideoRouteImport } from './routes/{-$locale}/video'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125MusicRouteImport } from './routes/{-$locale}/music'
import { Route as Char123LocaleChar125CodeRouteImport } from './routes/{-$locale}/code'
import { Route as Char123LocaleChar125AgentsRouteImport } from './routes/{-$locale}/agents'
import { Route as Char123LocaleChar125AffiliateDisclosureRouteImport } from './routes/{-$locale}/affiliate-disclosure'

const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125WritingRoute =
  Char123LocaleChar125WritingRouteImport.update({
    id: '/{-$locale}/writing',
    path: '/{-$locale}/writing',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125VoiceRoute =
  Char123LocaleChar125VoiceRouteImport.update({
    id: '/{-$locale}/voice',
    path: '/{-$locale}/voice',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125VideoRoute =
  Char123LocaleChar125VideoRouteImport.update({
    id: '/{-$locale}/video',
    path: '/{-$locale}/video',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/{-$locale}/terms',
    path: '/{-$locale}/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/{-$locale}/privacy',
    path: '/{-$locale}/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MusicRoute =
  Char123LocaleChar125MusicRouteImport.update({
    id: '/{-$locale}/music',
    path: '/{-$locale}/music',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CodeRoute =
  Char123LocaleChar125CodeRouteImport.update({
    id: '/{-$locale}/code',
    path: '/{-$locale}/code',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AgentsRoute =
  Char123LocaleChar125AgentsRouteImport.update({
    id: '/{-$locale}/agents',
    path: '/{-$locale}/agents',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AffiliateDisclosureRoute =
  Char123LocaleChar125AffiliateDisclosureRouteImport.update({
    id: '/{-$locale}/affiliate-disclosure',
    path: '/{-$locale}/affiliate-disclosure',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/go': typeof GoRoute
  '/{-$locale}/affiliate-disclosure': typeof Char123LocaleChar125AffiliateDisclosureRoute
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/code': typeof Char123LocaleChar125CodeRoute
  '/{-$locale}/music': typeof Char123LocaleChar125MusicRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/video': typeof Char123LocaleChar125VideoRoute
  '/{-$locale}/voice': typeof Char123LocaleChar125VoiceRoute
  '/{-$locale}/writing': typeof Char123LocaleChar125WritingRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/go': typeof GoRoute
  '/{-$locale}/affiliate-disclosure': typeof Char123LocaleChar125AffiliateDisclosureRoute
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/code': typeof Char123LocaleChar125CodeRoute
  '/{-$locale}/music': typeof Char123LocaleChar125MusicRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/video': typeof Char123LocaleChar125VideoRoute
  '/{-$locale}/voice': typeof Char123LocaleChar125VoiceRoute
  '/{-$locale}/writing': typeof Char123LocaleChar125WritingRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/go': typeof GoRoute
  '/{-$locale}/affiliate-disclosure': typeof Char123LocaleChar125AffiliateDisclosureRoute
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/code': typeof Char123LocaleChar125CodeRoute
  '/{-$locale}/music': typeof Char123LocaleChar125MusicRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/video': typeof Char123LocaleChar125VideoRoute
  '/{-$locale}/voice': typeof Char123LocaleChar125VoiceRoute
  '/{-$locale}/writing': typeof Char123LocaleChar125WritingRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/go'
    | '/{-$locale}/affiliate-disclosure'
    | '/{-$locale}/agents'
    | '/{-$locale}/code'
    | '/{-$locale}/music'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/video'
    | '/{-$locale}/voice'
    | '/{-$locale}/writing'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/go'
    | '/{-$locale}/affiliate-disclosure'
    | '/{-$locale}/agents'
    | '/{-$locale}/code'
    | '/{-$locale}/music'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/video'
    | '/{-$locale}/voice'
    | '/{-$locale}/writing'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/go'
    | '/{-$locale}/affiliate-disclosure'
    | '/{-$locale}/agents'
    | '/{-$locale}/code'
    | '/{-$locale}/music'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/video'
    | '/{-$locale}/voice'
    | '/{-$locale}/writing'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GoRoute: typeof GoRoute
  Char123LocaleChar125AffiliateDisclosureRoute: typeof Char123LocaleChar125AffiliateDisclosureRoute
  Char123LocaleChar125AgentsRoute: typeof Char123LocaleChar125AgentsRoute
  Char123LocaleChar125CodeRoute: typeof Char123LocaleChar125CodeRoute
  Char123LocaleChar125MusicRoute: typeof Char123LocaleChar125MusicRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125VideoRoute: typeof Char123LocaleChar125VideoRoute
  Char123LocaleChar125VoiceRoute: typeof Char123LocaleChar125VoiceRoute
  Char123LocaleChar125WritingRoute: typeof Char123LocaleChar125WritingRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/writing': {
      id: '/{-$locale}/writing'
      path: '/{-$locale}/writing'
      fullPath: '/{-$locale}/writing'
      preLoaderRoute: typeof Char123LocaleChar125WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/voice': {
      id: '/{-$locale}/voice'
      path: '/{-$locale}/voice'
      fullPath: '/{-$locale}/voice'
      preLoaderRoute: typeof Char123LocaleChar125VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/video': {
      id: '/{-$locale}/video'
      path: '/{-$locale}/video'
      fullPath: '/{-$locale}/video'
      preLoaderRoute: typeof Char123LocaleChar125VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/{-$locale}/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/{-$locale}/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/music': {
      id: '/{-$locale}/music'
      path: '/{-$locale}/music'
      fullPath: '/{-$locale}/music'
      preLoaderRoute: typeof Char123LocaleChar125MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/code': {
      id: '/{-$locale}/code'
      path: '/{-$locale}/code'
      fullPath: '/{-$locale}/code'
      preLoaderRoute: typeof Char123LocaleChar125CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/agents': {
      id: '/{-$locale}/agents'
      path: '/{-$locale}/agents'
      fullPath: '/{-$locale}/agents'
      preLoaderRoute: typeof Char123LocaleChar125AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/affiliate-disclosure': {
      id: '/{-$locale}/affiliate-disclosure'
      path: '/{-$locale}/affiliate-disclosure'
      fullPath: '/{-$locale}/affiliate-disclosure'
      preLoaderRoute: typeof Char123LocaleChar125AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GoRoute: GoRoute,
  Char123LocaleChar125AffiliateDisclosureRoute:
    Char123LocaleChar125AffiliateDisclosureRoute,
  Char123LocaleChar125AgentsRoute: Char123LocaleChar125AgentsRoute,
  Char123LocaleChar125CodeRoute: Char123LocaleChar125CodeRoute,
  Char123LocaleChar125MusicRoute: Char123LocaleChar125MusicRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125VideoRoute: Char123LocaleChar125VideoRoute,
  Char123LocaleChar125VoiceRoute: Char123LocaleChar125VoiceRoute,
  Char123LocaleChar125WritingRoute: Char123LocaleChar125WritingRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
